# Generated by Django 5.2.1 on 2025-05-17 20:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users_module', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='hashtags',
            field=models.CharField(blank=True, help_text='Comma-separated hashtags', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='customuser',
            name='income',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='customuser',
            name='orientation',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='customuser',
            name='profile_image',
            field=models.ImageField(blank=True, null=True, upload_to='profile_images/'),
        ),
    ]
